var krjsconfig = {
  krjs1: {
    hover: "<b><u>부산</u></b>",
    url: "https://www.busan.go.kr/index",
    target: "same_window", // use "new_window", "same_window", "modal", or "none"
    upColor: "#FFFFF3", //default color
    overColor: "#ECFFB3", //highlight color
    downColor: "#cae9af", //clicking color
    active: true, //true/false to activate/deactivate
  },
  krjs2: {
    hover: "<b><u>충청북도</u></b>",
    url: "https://www.chungbuk.go.kr/www/index.do",
    target: "same_window",
    upColor: "#f1ffc8",
    overColor: "#d9ff66",
    downColor: "#cae9af",
    active: true,
  },
  krjs3: {
    hover: "<b><u>충청남도</u></b>",
    url: "http://www.chungnam.go.kr/main.do",
    target: "same_window",
    upColor: "#d7f57a",
    overColor: "#beef2a",
    downColor: "#cae9af",
    active: true,
  },
  krjs4: {
    hover: "<b><u>대구</u></b>",
    url: "https://www.daegu.go.kr/index.do",
    target: "same_window",
    upColor: "#f1ffc8",
    overColor: "#d9ff66",
    downColor: "#cae9af",
    active: true,
  },
  krjs5: {
    hover: "<b><u>대전</u></b>",
    url: "https://www.daejeon.go.kr/",
    target: "modal",
    upColor: "#edff66",
    overColor: "#cbe600",
    downColor: "#cae9af",
    active: true,
  },
  krjs6: {
    hover: "<b><u>강원도</u></b>",
    url: "https://www.gangwon.to/gwtour",
    target: "same_window",
    upColor: "#E0E2E2",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs7: {
    hover: "<b><u>광주</u></b>",
    url: "http://www.gwangju.go.kr",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs8: {
    hover: "<b><u>경기도</u></b>",
    url: "https://www.gg.go.kr/",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs9: {
    hover: "<b><u>경상북도</u></b>",
    url: "https://www.gb.go.kr/",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs10: {
    hover: "<b><u>경상남도</u></b>",
    url: "https://www.gyeongnam.go.kr/index.gyeong",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs11: {
    hover: "<b><u>인천</u></b>",
    url: "https://www.incheon.go.kr/index",
    target: "same_window",
    upColor: "orange",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs12: {
    hover: "<b><u>제주도</u></b>",
    url: "https://www.jeju.go.kr/index.htm",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs13: {
    hover: "<b><u>전라북도</u></b>",
    url: "https://www.jeonbuk.go.kr/index.jeonbuk",
    target: "same_window",
    upColor: "#f1ffc8",
    overColor: "#d9ff66",
    downColor: "#cae9af",
    active: true,
  },
  krjs14: {
    hover: "<b><u>전라남도</u></b>",
    url: "https://www.namdokorea.com/",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs15: {
    hover: "<b><u>세종</u></b>",
    url: "https://www.sejong.go.kr/index.jsp",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs16: {
    hover: "<b><u>서울</u></b>",
    url: "https://www.seoul.go.kr/main/index.jsp",
    target: "same_window",
    upColor: "yellow",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  krjs17: {
    hover: "<b><u>울산</u></b>",
    url: "https://www.ulsan.go.kr/rep/index/",
    target: "same_window",
    upColor: "#FFFFF3",
    overColor: "#ECFFB3",
    downColor: "#cae9af",
    active: true,
  },
  general: {
    borderColor: "#9CA8B6",
    visibleNames: "#adadad",
  },
};
